author:
  name: Sebastian Bub
  email: sebastian@der-bub.de
  url: 'http://der-bub.de'
title: iOS Developer
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3131603191141039
  brandStrength: 0.4516649
  lightness: 0.5489419111981988
  brandColors:
    - '#E2DEDD'
    - '#1D2225'
    - '#867D60'
    - '#6C5625'
    - '#AAA28B'
  rhythmicContrast: 0.3560128945391625
typography_spectrum: 0.4871106
layout_spectrum: 0
name: der bub
